-- *****************************************************
-- ALUMNO: Jonathan Alejandro Sánchez Alcántara
-- MATERIA: DESARROLLO AVANZADO DE SISTEMAS (I.S.C.)
-- FECHA: 23 / Marzo / 2022
-- ******************************************************

CREATE DATABASE CONTROL_ACCESO;

USE CONTROL_ACCESO;

CREATE TABLE TIPO_USUARIO
(
	TIP_CVE_TIPOUSUARIO		INT 			NOT NULL	PRIMARY KEY AUTO_INCREMENT,
	TIP_DESCRIPCION			VARCHAR(20) 	NOT NULL
);

CREATE TABLE USUARIO
(
	USU_CVE_USUARIO			INT 			NOT NULL	PRIMARY KEY AUTO_INCREMENT,
	USU_NOMBRE				VARCHAR(20) 	NOT NULL,
	USU_APELLIDO_PATERNO	VARCHAR(20) 	NOT NULL,
	USU_APELLIDO_MATERNO	VARCHAR(20) 	NOT NULL,
	USU_USUARIO				VARCHAR(20) 	NOT NULL,
	USU_CONTRASENA			VARCHAR(20) 	NOT NULL,
	USU_RUTA				VARCHAR(200) 	NOT NULL,
	TIP_CVE_TIPOUSUARIO		INT 			NOT NULL,
	FOREIGN KEY (TIP_CVE_TIPOUSUARIO) REFERENCES TIPO_USUARIO(TIP_CVE_TIPOUSUARIO) 
);


-- (1) CREAR LA BASE DE DATOS Y LAS TABLAS
-- (2) INSERTAR 3 TIPOS DE USUARIO (ADMINISTRADOR, SUPERVISOR, OPERATIVO)
-- (3) INSERTAR UN USUARIO POR CADA TIPO DE USUARIO

-- ####################################################################################
-- (4) GENERAR UNA PROPUESTA CON LO SIGUIENTE:
--     DISEÑAR UNA CONSULTA (SELECT) PARA VALIDAR UN CONTROL DE ACCESO (USUARIO Y CONTRASEÑA) CON LAS
--     DOS TABLAS QUE TENEMOS

